# Minimal Mistakes theme configuration
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-gist
  - jekyll-sitemap
locale: "en-US"
title: "DownFlux Documentation"
description: "Archive of technical, API, unit, and balance design documentation."
url: "https://downflux.github.io"
baseurl: "/docs"
repository: "downflux/docs"
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/downflux"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/downfluxgame"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://reddit.com/r/downflux"
    - label: "Sitemap"
      icon: "fas fa-fw fa-sitemap"
      url: "/docs/sitemap"
# Custom default rendering.
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      author_profile: false
  - scope:
      path: "design"
      type: pages
    values:
      toc: true
      toc_label: "Contents"
      toc_icon: "list"
      classes: false

markdown: kramdown
